version: '3.4'

services: 
    apache:
        build: 
            context: ./php
        ports:
            - 80:80
        expose: 
            - 80  
        volumes:
            - ./public_html:/var/www/html
        depends_on:
            #- php
            - db
        links: 
            - db:db

    #php:
    #    image: php:7.3-rc-fpm-alpine
    #    volumes:
    #        - ./public_html:/var/www/html

    db:
        image: mariadb:latest
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ConsumerWebsite
            MYSQL_INITDB_SKIP_TZINFO: 1

    adminer:
        image: adminer
        ports:
            - 8080:8080